os:              osx
osx_image:       xcode10.1
env:
  - ENV=CI

before_install:
  - git clone https://${GIT_VAR}@git.bio-feed.org/BioFeed/plants-data dataset
install:
  - brew install python --force
  - brew switch python 3.6.5_1 # Python 3.7 doesn't work...
  - pip install -r requirements.txt

script:
  - python test.py
  - ls -lah

notifications:
  email:         false
